# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb2afdee25b38693e96b747818daa2da9fbaad15a0bcf7e4fdf49fdec82e7f061a5a4f836f8eff30327c4fea9bed7456dc551fce83d466f656ab8cab007818f1

test:
  secret_key_base: 7554ea2f6e8a21bcabbeb7c649199d03d2fb6a4d0fa252f0fcc802d01e3c68d443351b4166e42c78b19271eabb6d49df812cc5924fdde7a587d2a636c9a28cc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
